language: android
jdk:
- oraclejdk8
notifications:
  email: false
sudo: false
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
before_install:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_deploy:
  - echo " travis deploy +++++++++++++++++++++++++++++++++++"
  - git config --local user.name hawkwei0921
  - git config --local user.email hawk_wei@htc.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - printenv
  - ls -al
  - ls -al $TRAVIS_BUILD_DIR/
  - ls -al app/build/outputs/apk/

deploy:
  provider: releases
  api_key:
    secure: I7lqLNgBGVzXVNx0J9jgwfiRPWdeZFJwddN7ieISkwHmSgL29obS/udRNB6cnnjdRgS/9N471o/mnhJneCAYDtGYUv801JfffrqK8LFRIW6SyK79P+q8X+3wNLFV+/+HF0VMdiF4ZhySzEn4W0peycv5LX0sRUMTKFhXcErTXTqcGAJAh+qT/J5+EEGp1RxlXK5AhcpgCD8DNZq+YcvyVUB/lKLfZ9EhH+VAuXM4cmpDs1ueiHvCPrlOlmmjIu1sLnJt/jPiW1vZSuhUou+hW4m3hocV7L9beDHnKVGD6F3bFnjauIsuoD9HJ4VC0a9AgQma/QIqcBnjfq2i5waQEfX8D4rVkqhfMwU+55uPxaZVEMtNHnyKurD//+Vn95OqUKcPMK1FagGu9uuVomxHq6wowzuqUcLv61dbq8iLYesrOTMh+xWT9oiRDWDAZNa2ICFZPQ2URtCkip5Ijt7M3dM17k0yzO7er+ifIfIO9oFgk7RPP9ZUEfvKVDiBYJvebYou5fv764NF0iu/Mj/0g/GGS/nEhYaoBkYtQtMZDVTWoddbhRNrqKUvv/9XQiyNleTUvrf/YNv2ih8WpoGG3157Otm0231Wvn0mor0Qxsbay1TBTQ7NzJkGYW4wzBrIjgZ2uGq8Bk8ChlstwAxf90zhVszj/uOjHCvVY+iMhgU=
  file: app/build/outputs/apk/app-release-unsigned.apk
  on:
    repo: hawkwei0921/how-to-use-travis-ci
    tags: false

  overwrite: true
  skip_cleanup: true


